name: cs2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - tqdm
  - visdom
  - opencv
  - visdom
  - scikit-learn
  - pytorch
  - torchvision
  - pytorch-cuda=12.4
  - pip
  - scikit-image
  - pip:
    - SimpleITK

